// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKo4eo3ZNsKJfeo623yjnbBJzNWBZLfos',
    appId: '1:190169579590:web:1e57a3ff02835a81b58a47',
    messagingSenderId: '190169579590',
    projectId: 'nearbystore-4a026',
    authDomain: 'nearbystore-4a026.firebaseapp.com',
    storageBucket: 'nearbystore-4a026.appspot.com',
    measurementId: 'G-7ZS902JCNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4FyUhzaX-qoF9TEGHzfHvUyuK4e-ol94',
    appId: '1:190169579590:android:a6a4a933e23697aab58a47',
    messagingSenderId: '190169579590',
    projectId: 'nearbystore-4a026',
    storageBucket: 'nearbystore-4a026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA4Rn_10c0fNOON4fWfZ3Qd6VgQ1riY8I',
    appId: '1:190169579590:ios:7e2bba851970f81eb58a47',
    messagingSenderId: '190169579590',
    projectId: 'nearbystore-4a026',
    storageBucket: 'nearbystore-4a026.appspot.com',
    iosBundleId: 'com.example.nearByStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA4Rn_10c0fNOON4fWfZ3Qd6VgQ1riY8I',
    appId: '1:190169579590:ios:888fadbc3d642108b58a47',
    messagingSenderId: '190169579590',
    projectId: 'nearbystore-4a026',
    storageBucket: 'nearbystore-4a026.appspot.com',
    iosBundleId: 'com.example.nearByStore.RunnerTests',
  );
}
